# Generated by Django 2.0.1 on 2018-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_text', models.TextField(default='')),
                ('sugar', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
    ]
